services:
    postgres:
        image: postgres:17-alpine
        ports:
         - '5433:5432'
        volumes:
         - postgres:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=laravel
        - POSTGRES_USER=nannaluie
        - POSTGRES_PASSWORD=supersecretpassword
volumes:
    mysql:
    postgres:
